aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: x
    secret: x
  securityService:
    host: https://api-ci.aegcamp.com/security
  affiliateService:
    host: https://api-ci.aegcamp.com/affiliate
  fulfillmentService:
    host: https://api-ci.aegcamp.com/fulfillment