aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: rDMUB1fKPly5t2kw/UNjkp/AIAy6hjUSnkX7ZmkwiQA=
    secret: a7rrG6Cba4z4pu1DVVhxSlN9tRvlexqDsKNZp3it2+8=
  securityService:
    host: https://api-ci.aegcamp.com/security
  affiliateService:
    host: https://api-ci.aegcamp.com/affiliate
  fulfillmentService:
    host: https://api-ci.aegcamp.com/fulfillment