aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: x
    secret: x
  securityService:
    host: http://localhost:3000/v1
    swagger: http://localhost:3000/v1/swagger
  affiliateService:
    host: http://localhost:3002/v1
    swagger: http://localhost:3002/v1/swagger
  fulfillmentService:
    host: http://localhost:3005/v1
    swagger: http://localhost:3005/v1/swagger