aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: x
    secret: x
  securityService:
    host: http://localhost:3000
    swagger: http://localhost:3000/swagger
  affiliateService:
    host: http://localhost:3002
    swagger: http://localhost:3002/swagger
  fulfillmentService:
    host: http://localhost:3005
    swagger: http://localhost:3005/swagger