aeg-sdk:
  securityService:
    host: http://localhost:3000/v1
    swagger: http://localhost:3000/v1/swagger
  affiliateService:
    host: http://localhost:3002/v1
    swagger: http://localhost:3002/v1/swagger