aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: rDMUB1fKPly5t2kw/UNjkp/AIAy6hjUSnkX7ZmkwiQA=
    secret: a7rrG6Cba4z4pu1DVVhxSlN9tRvlexqDsKNZp3it2+8=
  securityService:
    host: http://localhost:3000
    swagger: http://localhost:3000/swagger
  affiliateService:
    host: http://localhost:3002
    swagger: http://localhost:3002/swagger
  fulfillmentService:
    host: http://localhost:3005
    swagger: http://localhost:3005/swagger