#local

securityService:
  host: http://localhost:3000/v1
  swagger: http://localhost:3000/v1/swagger

affiliateService:
  host: http://localhost:3002/v1
  swagger: http://localhost:3002/v1/swagger

#production

#securityService:
#  host: https://api.aegcamp.com/v1/security
#
#affiliateService:
#  host: https://api.aegcamp.com/v1/affiliate

#ci

#securityService:
#  host: https://api-ci.aegcamp.com/v1/security
#
#affiliateService:
#  host: https://api-ci.aegcamp.com/v1/affiliate