securityService:
  host: http://localhost:3000/v1
  swagger: http://localhost:3000/v1/swagger

affiliateService:
  host: http://localhost:3002/v1
  swagger: http://localhost:3002/v1/swagger

stormpath:
  apiKey:
    id: 3555F4IHMVXTSB0WUZFJQZQPJ
    secret: qSAhf1HC39wmnz1/UVKvpwyfVWPywrqE9Te8CdwGGww
  application:
    href: https://api.stormpath.com/v1/applications/6x9i1BvcTdaUTjbWhYhNbx