securityService:
  host: http://localhost:3000/v1
  swagger: http://localhost:3000/v1/swagger

affiliateService:
  host: http://localhost:3002/v1
  swagger: http://localhost:3002/v1/swagger

#securityService:
#  host: https://api.aegcamp.com/v1/security
#
#affiliateService:
#  host: https://api.aegcamp.com/v1/affiliate

#securityService:
#  host: https://api-ci.aegcamp.com/v1/security
#
#affiliateService:
#  host: https://api-ci.aegcamp.com/v1/affiliate

#production

#stormpath:
#  apiKey:
#    id: 3555F4IHMVXTSB0WUZFJQZQPJ
#    secret: qSAhf1HC39wmnz1/UVKvpwyfVWPywrqE9Te8CdwGGww
#  application:
#    href: https://api.stormpath.com/v1/applications/6x9i1BvcTdaUTjbWhYhNbx

#production

#ci:

stormpath:
  apiKey:
    id: 4MW5I4WPBI0LRCR8OKTAGTAW7
    secret: 6+D5saEKgPUToaQdbPdvrdN8aJJkkOwwDNqPzaEteeA
  application:
    href: https://api.stormpath.com/v1/applications/X3drpV1iQTPh1uSwLuUpW

aws:
  public: "AKIAI6UQYWI5EOZXIN7A"
  private: "I2Gv3Z22YsEHEumeFLNKBCsCptT97t2kttBVCnnx"
  ses:
    from: 'donotreply@aegaffiliate.com'
    zone: 'https://email.us-west-2.amazonaws.com'