aeg-sdk:
  scope: 'affiliate:service'
  apiKey:
    id: x
    secret: x
  securityService:
    host: https://api.aegcamp.com/v1/security
  affiliateService:
    host: https://api.aegcamp.com/v1/affiliate
  fulfillmentService:
    host: https://api.aegcamp.com/v1/fulfillment