logger:
  transports:
    - type: console
      level: debug
    - type: file
      level: debug
      filename: logs/aeg-sdk.log
securityService:
  host: https://security.aegcamp.com
  baseUrl: /v1
stormpath:
  apiKey:
    id: 3555F4IHMVXTSB0WUZFJQZQPJ
    secret: qSAhf1HC39wmnz1/UVKvpwyfVWPywrqE9Te8CdwGGww
  application:
    href: https://api.stormpath.com/v1/applications/6x9i1BvcTdaUTjbWhYhNbx