logger:
  transports:
    - type: console
      level: debug
    - type: file
      level: debug
      filename: logs/aeg-sdk.log
securityService:
  host: http://security-service.elasticbeanstalk.com
  baseUrl: /v1